# Generated by Django 3.1.10 on 2023-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20230624_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
