# Generated by Django 3.1.10 on 2023-06-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20230625_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='email',
        ),
    ]
