# Generated by Django 3.1.10 on 2023-06-25 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_remove_public_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='private_file_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='private',
            name='user',
        ),
        migrations.DeleteModel(
            name='music_user',
        ),
        migrations.DeleteModel(
            name='private',
        ),
    ]
